try
	throw("Exception")
catch {
	if($exception.message.length > 0)
		return("crazy exception happened")
}